// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.mysql;

import org.jspecify.annotations.Nullable;

public record BooksByTagsRow (
    int bookId,
    String title,
    @Nullable String name,
    String isbn,
    String tags
) {}

