// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.mysql;

import java.time.LocalDateTime;

public record Book (
    int bookId,
    int authorId,
    String isbn,
    BooksBookType bookType,
    String title,
    int yr,
    LocalDateTime available,
    String tags
) {}

