// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.mysql;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import org.jspecify.annotations.Nullable;

public interface Queries {
  
  List<BooksByTagsRow> booksByTags(String tags) throws SQLException;
  
  List<Book> booksByTitleYear(String title, int yr) throws SQLException;
  
  long createAuthor(String name) throws SQLException;
  
  long createBook(
      int authorId,
      String isbn,
      BooksBookType bookType,
      String title,
      int yr,
      LocalDateTime available,
      String tags) throws SQLException;
  
  void deleteAuthorBeforeYear(int yr, int authorId) throws SQLException;
  
  void deleteBook(int bookId) throws SQLException;
  
  @Nullable Author getAuthor(int authorId) throws SQLException;
  
  @Nullable Book getBook(int bookId) throws SQLException;
  
  void updateBook(
      String title,
      String tags,
      int bookId) throws SQLException;
  
  void updateBookISBN(
      String title,
      String tags,
      String isbn,
      int bookId) throws SQLException;
  
}

