// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.mysql;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

public final class QueriesImpl implements Queries {
  private final Connection conn;

  public QueriesImpl(Connection conn) {
    this.conn = conn;
  }
  
  private static final String booksByTags = """
SELECT
  book_id,
  title,
  name,
  isbn,
  tags
FROM books
LEFT JOIN authors ON books.author_id = authors.author_id
WHERE tags = ?
""";
  
  @Override
  public List<BooksByTagsRow> booksByTags(String tags) throws SQLException {
    try (var stmt = conn.prepareStatement(booksByTags)) {
      stmt.setString(1, tags);

      var results = stmt.executeQuery();
      var ret = new ArrayList<BooksByTagsRow>();
      while (results.next()) {
        ret.add(new BooksByTagsRow(
                results.getInt(1),
                results.getString(2),
                results.getString(3),
                results.getString(4),
                results.getString(5)
            ));
      }
      return ret;
    }
  }
  
  private static final String booksByTitleYear = """
SELECT book_id, author_id, isbn, book_type, title, yr, available, tags FROM books
WHERE title = ? AND yr = ?
""";
  
  @Override
  public List<Book> booksByTitleYear(String title, int yr) throws SQLException {
    try (var stmt = conn.prepareStatement(booksByTitleYear)) {
      stmt.setString(1, title);
          stmt.setInt(2, yr);

      var results = stmt.executeQuery();
      var ret = new ArrayList<Book>();
      while (results.next()) {
        ret.add(new Book(
                results.getInt(1),
                results.getInt(2),
                results.getString(3),
                Objects.requireNonNull(BooksBookType.lookup(results.getString(4))),
                results.getString(5),
                results.getInt(6),
                results.getObject(7, LocalDateTime.class),
                results.getString(8)
            ));
      }
      return ret;
    }
  }
  
  private static final String createAuthor = """
INSERT INTO authors (name) VALUES (?)
""";
  
  @Override
  public long createAuthor(String name) throws SQLException {
    try (var stmt = conn.prepareStatement(createAuthor, Statement.RETURN_GENERATED_KEYS)) {
      stmt.setString(1, name);

      stmt.execute();

      var results = stmt.getGeneratedKeys();
      if (!results.next()) {
        throw new SQLException("no generated key returned");
      }
      return results.getLong(1);
    }
  }
  
  private static final String createBook = """
INSERT INTO books (
    author_id,
    isbn,
    book_type,
    title,
    yr,
    available,
    tags
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
""";
  
  @Override
  public long createBook(
      int authorId,
      String isbn,
      BooksBookType bookType,
      String title,
      int yr,
      LocalDateTime available,
      String tags) throws SQLException {
    try (var stmt = conn.prepareStatement(createBook, Statement.RETURN_GENERATED_KEYS)) {
      stmt.setInt(1, authorId);
          stmt.setString(2, isbn);
          stmt.setString(3, bookType.value());
          stmt.setString(4, title);
          stmt.setInt(5, yr);
          stmt.setObject(6, available);
          stmt.setString(7, tags);

      stmt.execute();

      var results = stmt.getGeneratedKeys();
      if (!results.next()) {
        throw new SQLException("no generated key returned");
      }
      return results.getLong(1);
    }
  }
  
  private static final String deleteAuthorBeforeYear = """
DELETE FROM books
WHERE yr < ? AND author_id = ?
""";
  
  @Override
  public void deleteAuthorBeforeYear(int yr, int authorId) throws SQLException {
    try (var stmt = conn.prepareStatement(deleteAuthorBeforeYear)) {
      stmt.setInt(1, yr);
          stmt.setInt(2, authorId);

      stmt.execute();
    }
  }
  
  private static final String deleteBook = """
DELETE FROM books
WHERE book_id = ?
""";
  
  @Override
  public void deleteBook(int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(deleteBook)) {
      stmt.setInt(1, bookId);

      stmt.execute();
    }
  }
  
  private static final String getAuthor = """
SELECT author_id, name FROM authors
WHERE author_id = ?
""";
  
  @Override
  public @Nullable Author getAuthor(int authorId) throws SQLException {
    try (var stmt = conn.prepareStatement(getAuthor)) {
      stmt.setInt(1, authorId);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Author(
                results.getInt(1),
                results.getString(2)
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String getBook = """
SELECT book_id, author_id, isbn, book_type, title, yr, available, tags FROM books
WHERE book_id = ?
""";
  
  @Override
  public @Nullable Book getBook(int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(getBook)) {
      stmt.setInt(1, bookId);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Book(
                results.getInt(1),
                results.getInt(2),
                results.getString(3),
                Objects.requireNonNull(BooksBookType.lookup(results.getString(4))),
                results.getString(5),
                results.getInt(6),
                results.getObject(7, LocalDateTime.class),
                results.getString(8)
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String updateBook = """
UPDATE books
SET title = ?, tags = ?
WHERE book_id = ?
""";
  
  @Override
  public void updateBook(
      String title,
      String tags,
      int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(updateBook)) {
      stmt.setString(1, title);
          stmt.setString(2, tags);
          stmt.setInt(3, bookId);

      stmt.execute();
    }
  }
  
  private static final String updateBookISBN = """
UPDATE books
SET title = ?, tags = ?, isbn = ?
WHERE book_id = ?
""";
  
  @Override
  public void updateBookISBN(
      String title,
      String tags,
      String isbn,
      int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(updateBookISBN)) {
      stmt.setString(1, title);
          stmt.setString(2, tags);
          stmt.setString(3, isbn);
          stmt.setInt(4, bookId);

      stmt.execute();
    }
  }
  
}

