// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.ondeck.postgresql;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import org.jspecify.annotations.Nullable;

public interface Queries {
  // Create a new city. The slug must be unique.
  // This is the second line of the comment
  // This is the third line
  
  @Nullable City createCity(String name, String slug) throws SQLException;
  
  @Nullable Integer createVenue(
      String slug,
      String name,
      String city,
      String spotifyPlaylist,
      Status status,
      List<Status> statuses,
      List<String> tags) throws SQLException;
  
  void deleteVenue(String slug) throws SQLException;
  
  @Nullable City getCity(String slug) throws SQLException;
  
  @Nullable Venue getVenue(String slug, String city) throws SQLException;
  
  List<City> listCities() throws SQLException;
  
  List<Venue> listVenues(String city) throws SQLException;
  
  void updateCityName(String name, String slug) throws SQLException;
  
  @Nullable Integer updateVenueName(String name, String slug) throws SQLException;
  
  List<VenueCountByCityRow> venueCountByCity() throws SQLException;
  
}

