// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.ondeck.postgresql;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

// Venues can be either open or closed
public enum Status {
  OPEN("op!en"),
  CLOSED("clo@sed");

  private final String value;

  Status(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  private static final Map<String, Status> LOOKUP =
      Arrays.stream(values()).collect(Collectors.toMap(Status::value, v -> v));

  public static @Nullable Status lookup(String value) {
    return LOOKUP.get(value);
  }
}

