// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.ondeck.postgresql;

import java.time.LocalDateTime;
import java.util.List;
import org.jspecify.annotations.Nullable;

// Venues are places where muisc happens
public record Venue (
    int id,
    Status status,
    List<Status> statuses,
    
    // This value appears in public URLs
    String slug,
    String name,
    String city,
    String spotifyPlaylist,
    @Nullable String songkickId,
    List<String> tags,
    LocalDateTime createdAt
) {}

