// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.ondeck.mysql;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

public final class QueriesImpl implements Queries {
  private final Connection conn;

  public QueriesImpl(Connection conn) {
    this.conn = conn;
  }
  
  private static final String createCity = """
INSERT INTO city (
    name,
    slug
) VALUES (
    ?,
    ? 
)
""";
  
  @Override
  public void createCity(String name, String slug) throws SQLException {
    try (var stmt = conn.prepareStatement(createCity)) {
      stmt.setString(1, name);
          stmt.setString(2, slug);

      stmt.execute();
    }
  }
  
  private static final String createVenue = """
INSERT INTO venue (
    slug,
    name,
    city,
    created_at,
    spotify_playlist,
    status,
    statuses,
    tags
) VALUES (
    ?,
    ?,
    ?,
    NOW(),
    ?,
    ?,
    ?,
    ?
)
""";
  
  @Override
  public long createVenue(
      String slug,
      String name,
      String city,
      String spotifyPlaylist,
      VenueStatus status,
      @Nullable String statuses,
      @Nullable String tags) throws SQLException {
    try (var stmt = conn.prepareStatement(createVenue, Statement.RETURN_GENERATED_KEYS)) {
      stmt.setString(1, slug);
          stmt.setString(2, name);
          stmt.setString(3, city);
          stmt.setString(4, spotifyPlaylist);
          stmt.setString(5, status.value());
          stmt.setString(6, statuses);
          stmt.setString(7, tags);

      stmt.execute();

      var results = stmt.getGeneratedKeys();
      if (!results.next()) {
        throw new SQLException("no generated key returned");
      }
      return results.getLong(1);
    }
  }
  
  private static final String deleteVenue = """
DELETE FROM venue
WHERE slug = ? AND slug = ?
""";
  
  @Override
  public void deleteVenue(String slug, String slug_2) throws SQLException {
    try (var stmt = conn.prepareStatement(deleteVenue)) {
      stmt.setString(1, slug);
          stmt.setString(2, slug_2);

      stmt.execute();
    }
  }
  
  private static final String getCity = """
SELECT slug, name
FROM city
WHERE slug = ?
""";
  
  @Override
  public @Nullable City getCity(String slug) throws SQLException {
    try (var stmt = conn.prepareStatement(getCity)) {
      stmt.setString(1, slug);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new City(
                results.getString(1),
                results.getString(2)
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String getVenue = """
SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE slug = ? AND city = ?
""";
  
  @Override
  public @Nullable Venue getVenue(String slug, String city) throws SQLException {
    try (var stmt = conn.prepareStatement(getVenue)) {
      stmt.setString(1, slug);
          stmt.setString(2, city);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Venue(
                results.getLong(1),
                Objects.requireNonNull(VenueStatus.lookup(results.getString(2))),
                results.getString(3),
                results.getString(4),
                results.getString(5),
                results.getString(6),
                results.getString(7),
                results.getString(8),
                results.getString(9),
                results.getTimestamp(10).toInstant()
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String listCities = """
SELECT slug, name
FROM city
ORDER BY name
""";
  
  @Override
  public List<City> listCities() throws SQLException {
    try (var stmt = conn.prepareStatement(listCities)) {
      
      var results = stmt.executeQuery();
      var ret = new ArrayList<City>();
      while (results.next()) {
        ret.add(new City(
                results.getString(1),
                results.getString(2)
            ));
      }
      return ret;
    }
  }
  
  private static final String listVenues = """
SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE city = ?
ORDER BY name
""";
  
  @Override
  public List<Venue> listVenues(String city) throws SQLException {
    try (var stmt = conn.prepareStatement(listVenues)) {
      stmt.setString(1, city);

      var results = stmt.executeQuery();
      var ret = new ArrayList<Venue>();
      while (results.next()) {
        ret.add(new Venue(
                results.getLong(1),
                Objects.requireNonNull(VenueStatus.lookup(results.getString(2))),
                results.getString(3),
                results.getString(4),
                results.getString(5),
                results.getString(6),
                results.getString(7),
                results.getString(8),
                results.getString(9),
                results.getTimestamp(10).toInstant()
            ));
      }
      return ret;
    }
  }
  
  private static final String updateCityName = """
UPDATE city
SET name = ?
WHERE slug = ?
""";
  
  @Override
  public void updateCityName(String name, String slug) throws SQLException {
    try (var stmt = conn.prepareStatement(updateCityName)) {
      stmt.setString(1, name);
          stmt.setString(2, slug);

      stmt.execute();
    }
  }
  
  private static final String updateVenueName = """
UPDATE venue
SET name = ?
WHERE slug = ?
""";
  
  @Override
  public void updateVenueName(String name, String slug) throws SQLException {
    try (var stmt = conn.prepareStatement(updateVenueName)) {
      stmt.setString(1, name);
          stmt.setString(2, slug);

      stmt.execute();
    }
  }
  
  private static final String venueCountByCity = """
SELECT
    city,
    count(*)
FROM venue
GROUP BY 1
ORDER BY 1
""";
  
  @Override
  public List<VenueCountByCityRow> venueCountByCity() throws SQLException {
    try (var stmt = conn.prepareStatement(venueCountByCity)) {
      
      var results = stmt.executeQuery();
      var ret = new ArrayList<VenueCountByCityRow>();
      while (results.next()) {
        ret.add(new VenueCountByCityRow(
                results.getString(1),
                results.getLong(2)
            ));
      }
      return ret;
    }
  }
  
}

