// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.ondeck.mysql;

import java.sql.SQLException;
import java.time.Instant;
import java.util.List;
import org.jspecify.annotations.Nullable;

public interface Queries {
  
  void createCity(String name, String slug) throws SQLException;
  
  long createVenue(
      String slug,
      String name,
      String city,
      String spotifyPlaylist,
      VenueStatus status,
      @Nullable String statuses,
      @Nullable String tags) throws SQLException;
  
  void deleteVenue(String slug, String slug_2) throws SQLException;
  
  @Nullable City getCity(String slug) throws SQLException;
  
  @Nullable Venue getVenue(String slug, String city) throws SQLException;
  
  List<City> listCities() throws SQLException;
  
  List<Venue> listVenues(String city) throws SQLException;
  
  void updateCityName(String name, String slug) throws SQLException;
  
  void updateVenueName(String name, String slug) throws SQLException;
  
  List<VenueCountByCityRow> venueCountByCity() throws SQLException;
  
}

