// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.ondeck.mysql;

import java.time.Instant;
import org.jspecify.annotations.Nullable;

// Venues are places where muisc happens
public record Venue (
    long id,
    
    // Venues can be either open or closed
    VenueStatus status,
    @Nullable String statuses,
    
    // This value appears in public URLs
    String slug,
    String name,
    String city,
    String spotifyPlaylist,
    @Nullable String songkickId,
    @Nullable String tags,
    Instant createdAt
) {}

