// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.ondeck.mysql;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

public enum VenueStatus {
  OPEN("open"),
  CLOSED("closed");

  private final String value;

  VenueStatus(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  private static final Map<String, VenueStatus> LOOKUP =
      Arrays.stream(values()).collect(Collectors.toMap(VenueStatus::value, v -> v));

  public static @Nullable VenueStatus lookup(String value) {
    return LOOKUP.get(value);
  }
}

