// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.authors.postgresql;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.jspecify.annotations.Nullable;

public final class QueriesImpl implements Queries {
  private final Connection conn;

  public QueriesImpl(Connection conn) {
    this.conn = conn;
  }
  
  private static final String createAuthor = """
INSERT INTO authors (
          name, bio
) VALUES (
  ?, ?
)
RETURNING id, name, bio
""";
  
  @Override
  public @Nullable Author createAuthor(String name, @Nullable String bio) throws SQLException {
    try (var stmt = conn.prepareStatement(createAuthor)) {
      stmt.setString(1, name);
          stmt.setString(2, bio);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Author(
                results.getLong(1),
                results.getString(2),
                results.getString(3)
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String deleteAuthor = """
DELETE FROM authors
WHERE id = ?
""";
  
  @Override
  public void deleteAuthor(long id) throws SQLException {
    try (var stmt = conn.prepareStatement(deleteAuthor)) {
      stmt.setLong(1, id);

      stmt.execute();
    }
  }
  
  private static final String getAuthor = """
SELECT id, name, bio FROM authors
WHERE id = ? LIMIT 1
""";
  
  @Override
  public @Nullable Author getAuthor(long id) throws SQLException {
    try (var stmt = conn.prepareStatement(getAuthor)) {
      stmt.setLong(1, id);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Author(
                results.getLong(1),
                results.getString(2),
                results.getString(3)
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String listAuthors = """
SELECT id, name, bio FROM authors
ORDER BY name
""";
  
  @Override
  public List<Author> listAuthors() throws SQLException {
    try (var stmt = conn.prepareStatement(listAuthors)) {
      
      var results = stmt.executeQuery();
      var ret = new ArrayList<Author>();
      while (results.next()) {
        ret.add(new Author(
                results.getLong(1),
                results.getString(2),
                results.getString(3)
            ));
      }
      return ret;
    }
  }
  
}

