// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.authors.mysql;

import org.jspecify.annotations.Nullable;

public record Author (
    long id,
    String name,
    @Nullable String bio
) {}

