// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.authors.mysql;

import java.sql.SQLException;
import java.util.List;
import org.jspecify.annotations.Nullable;

public interface Queries {
  
  long createAuthor(String name, @Nullable String bio) throws SQLException;
  
  void deleteAuthor(long id) throws SQLException;
  
  @Nullable Author getAuthor(long id) throws SQLException;
  
  List<Author> listAuthors() throws SQLException;
  
}

