// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.jets;

public record Jet (
    int id,
    int pilotId,
    int age,
    String name,
    String color
) {}

