// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.jets;

import java.sql.SQLException;
import java.util.List;
import org.jspecify.annotations.Nullable;

public interface Queries {
  
  @Nullable Long countPilots() throws SQLException;
  
  void deletePilot(int id) throws SQLException;
  
  List<Pilot> listPilots() throws SQLException;
  
}

