// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.jets;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.jspecify.annotations.Nullable;

public final class QueriesImpl implements Queries {
  private final Connection conn;

  public QueriesImpl(Connection conn) {
    this.conn = conn;
  }
  
  private static final String countPilots = """
SELECT COUNT(*) FROM pilots
""";
  
  @Override
  public @Nullable Long countPilots() throws SQLException {
    try (var stmt = conn.prepareStatement(countPilots)) {
      
      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = results.getLong(1);
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String deletePilot = """
DELETE FROM pilots WHERE id = ?
""";
  
  @Override
  public void deletePilot(int id) throws SQLException {
    try (var stmt = conn.prepareStatement(deletePilot)) {
      stmt.setInt(1, id);

      stmt.execute();
    }
  }
  
  private static final String listPilots = """
SELECT id, name FROM pilots LIMIT 5
""";
  
  @Override
  public List<Pilot> listPilots() throws SQLException {
    try (var stmt = conn.prepareStatement(listPilots)) {
      
      var results = stmt.executeQuery();
      var ret = new ArrayList<Pilot>();
      while (results.next()) {
        ret.add(new Pilot(
                results.getInt(1),
                results.getString(2)
            ));
      }
      return ret;
    }
  }
  
}

