// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.postgresql;

import java.time.OffsetDateTime;
import java.util.List;

public record Book (
    int bookId,
    int authorId,
    String isbn,
    BookType bookType,
    String title,
    int year,
    OffsetDateTime available,
    List<String> tags
) {}

