// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.postgresql;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

public enum BookType {
  FICTION("FICTION"),
  NONFICTION("NONFICTION");

  private final String value;

  BookType(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  private static final Map<String, BookType> LOOKUP =
      Arrays.stream(values()).collect(Collectors.toMap(BookType::value, v -> v));

  public static @Nullable BookType lookup(String value) {
    return LOOKUP.get(value);
  }
}

