// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.postgresql;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

public final class QueriesImpl implements Queries {
  private final Connection conn;

  public QueriesImpl(Connection conn) {
    this.conn = conn;
  }
  
  private static final String booksByTags = """
SELECT 
  book_id,
  title,
  name,
  isbn,
  tags
FROM books
LEFT JOIN authors ON books.author_id = authors.author_id
WHERE tags && ?::varchar[]
""";
  
  @Override
  public List<BooksByTagsRow> booksByTags(List<String> dollar1) throws SQLException {
    try (var stmt = conn.prepareStatement(booksByTags)) {
      stmt.setArray(1, conn.createArrayOf("pg_catalog.varchar", dollar1.toArray(new String[0])));

      var results = stmt.executeQuery();
      var ret = new ArrayList<BooksByTagsRow>();
      while (results.next()) {
        ret.add(new BooksByTagsRow(
                results.getInt(1),
                results.getString(2),
                results.getString(3),
                results.getString(4),
                Arrays.asList((String[]) results.getArray(5).getArray())
            ));
      }
      return ret;
    }
  }
  
  private static final String booksByTitleYear = """
SELECT book_id, author_id, isbn, book_type, title, year, available, tags FROM books
WHERE title = ? AND year = ?
""";
  
  @Override
  public List<Book> booksByTitleYear(String title, int year) throws SQLException {
    try (var stmt = conn.prepareStatement(booksByTitleYear)) {
      stmt.setString(1, title);
          stmt.setInt(2, year);

      var results = stmt.executeQuery();
      var ret = new ArrayList<Book>();
      while (results.next()) {
        ret.add(new Book(
                results.getInt(1),
                results.getInt(2),
                results.getString(3),
                Objects.requireNonNull(BookType.lookup(results.getString(4))),
                results.getString(5),
                results.getInt(6),
                results.getObject(7, OffsetDateTime.class),
                Arrays.asList((String[]) results.getArray(8).getArray())
            ));
      }
      return ret;
    }
  }
  
  private static final String createAuthor = """
INSERT INTO authors (name) VALUES (?)
RETURNING author_id, name
""";
  
  @Override
  public @Nullable Author createAuthor(String name) throws SQLException {
    try (var stmt = conn.prepareStatement(createAuthor)) {
      stmt.setString(1, name);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Author(
                results.getInt(1),
                results.getString(2)
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String createBook = """
INSERT INTO books (
    author_id,
    isbn,
    book_type,
    title,
    year,
    available,
    tags
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING book_id, author_id, isbn, book_type, title, year, available, tags
""";
  
  @Override
  public @Nullable Book createBook(
      int authorId,
      String isbn,
      BookType bookType,
      String title,
      int year,
      OffsetDateTime available,
      List<String> tags) throws SQLException {
    try (var stmt = conn.prepareStatement(createBook)) {
      stmt.setInt(1, authorId);
          stmt.setString(2, isbn);
          stmt.setObject(3, bookType.value(), Types.OTHER);
          stmt.setString(4, title);
          stmt.setInt(5, year);
          stmt.setObject(6, available);
          stmt.setArray(7, conn.createArrayOf("pg_catalog.varchar", tags.toArray(new String[0])));

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Book(
                results.getInt(1),
                results.getInt(2),
                results.getString(3),
                Objects.requireNonNull(BookType.lookup(results.getString(4))),
                results.getString(5),
                results.getInt(6),
                results.getObject(7, OffsetDateTime.class),
                Arrays.asList((String[]) results.getArray(8).getArray())
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String deleteBook = """
DELETE FROM books
WHERE book_id = ?
""";
  
  @Override
  public void deleteBook(int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(deleteBook)) {
      stmt.setInt(1, bookId);

      stmt.execute();
    }
  }
  
  private static final String getAuthor = """
SELECT author_id, name FROM authors
WHERE author_id = ?
""";
  
  @Override
  public @Nullable Author getAuthor(int authorId) throws SQLException {
    try (var stmt = conn.prepareStatement(getAuthor)) {
      stmt.setInt(1, authorId);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Author(
                results.getInt(1),
                results.getString(2)
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String getBook = """
SELECT book_id, author_id, isbn, book_type, title, year, available, tags FROM books
WHERE book_id = ?
""";
  
  @Override
  public @Nullable Book getBook(int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(getBook)) {
      stmt.setInt(1, bookId);

      var results = stmt.executeQuery();
      if (!results.next()) {
        return null;
      }
      var ret = new Book(
                results.getInt(1),
                results.getInt(2),
                results.getString(3),
                Objects.requireNonNull(BookType.lookup(results.getString(4))),
                results.getString(5),
                results.getInt(6),
                results.getObject(7, OffsetDateTime.class),
                Arrays.asList((String[]) results.getArray(8).getArray())
            );
      if (results.next()) {
        throw new SQLException("expected one row in result set, but got many");
      }
      return ret;
    }
  }
  
  private static final String updateBook = """
UPDATE books
SET title = ?, tags = ?
WHERE book_id = ?
""";
  
  @Override
  public void updateBook(
      String title,
      List<String> tags,
      int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(updateBook)) {
      stmt.setString(1, title);
          stmt.setArray(2, conn.createArrayOf("pg_catalog.varchar", tags.toArray(new String[0])));
          stmt.setInt(3, bookId);

      stmt.execute();
    }
  }
  
  private static final String updateBookISBN = """
UPDATE books
SET title = ?, tags = ?, isbn = ?
WHERE book_id = ?
""";
  
  @Override
  public void updateBookISBN(
      String title,
      List<String> tags,
      String isbn,
      int bookId) throws SQLException {
    try (var stmt = conn.prepareStatement(updateBookISBN)) {
      stmt.setString(1, title);
          stmt.setArray(2, conn.createArrayOf("pg_catalog.varchar", tags.toArray(new String[0])));
          stmt.setString(3, isbn);
          stmt.setInt(4, bookId);

      stmt.execute();
    }
  }
  
}

