// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
package com.example.booktest.postgresql;

import java.sql.SQLException;
import java.time.OffsetDateTime;
import java.util.List;
import org.jspecify.annotations.Nullable;

public interface Queries {
  
  List<BooksByTagsRow> booksByTags(List<String> dollar1) throws SQLException;
  
  List<Book> booksByTitleYear(String title, int year) throws SQLException;
  
  @Nullable Author createAuthor(String name) throws SQLException;
  
  @Nullable Book createBook(
      int authorId,
      String isbn,
      BookType bookType,
      String title,
      int year,
      OffsetDateTime available,
      List<String> tags) throws SQLException;
  
  void deleteBook(int bookId) throws SQLException;
  
  @Nullable Author getAuthor(int authorId) throws SQLException;
  
  @Nullable Book getBook(int bookId) throws SQLException;
  
  void updateBook(
      String title,
      List<String> tags,
      int bookId) throws SQLException;
  
  void updateBookISBN(
      String title,
      List<String> tags,
      String isbn,
      int bookId) throws SQLException;
  
}

